"""phase11_ai_initial_schema

Revision ID: b49ce07b805f
Revises: 
Create Date: 2026-05-16 10:43:44.064358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b49ce07b805f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_mlops_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('candidate_version', sa.Integer(), nullable=True),
    sa.Column('champion_version', sa.Integer(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_mlops_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_mlops_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_mlops_logs_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('ai_model_registry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_rows_used', sa.Integer(), nullable=False),
    sa.Column('training_source', sa.String(length=50), nullable=True),
    sa.Column('holdout_mae', sa.Float(), nullable=True),
    sa.Column('model_path', sa.String(length=500), nullable=False),
    sa.Column('feature_list', sa.Text(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_model_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_model_registry_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_model_registry_version'), ['version'], unique=True)

    op.create_table('ai_forecasts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_version', sa.Integer(), nullable=False),
    sa.Column('store_ref', sa.String(length=64), nullable=False),
    sa.Column('product_ref', sa.String(length=64), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('horizon', sa.String(length=10), nullable=False),
    sa.Column('predicted_qty', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_version'], ['ai_model_registry.version'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_forecasts_model_version'), ['model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_forecasts_product_ref'), ['product_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_forecasts_store_ref'), ['store_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_forecasts_target_date'), ['target_date'], unique=False)

    op.create_table('ai_forecast_actuals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('forecast_id', sa.Uuid(), nullable=False),
    sa.Column('actual_qty', sa.Float(), nullable=False),
    sa.Column('abs_error', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['ai_forecasts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forecast_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_forecast_actuals')
    with op.batch_alter_table('ai_forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_forecasts_target_date'))
        batch_op.drop_index(batch_op.f('ix_ai_forecasts_store_ref'))
        batch_op.drop_index(batch_op.f('ix_ai_forecasts_product_ref'))
        batch_op.drop_index(batch_op.f('ix_ai_forecasts_model_version'))

    op.drop_table('ai_forecasts')
    with op.batch_alter_table('ai_model_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_model_registry_version'))
        batch_op.drop_index(batch_op.f('ix_ai_model_registry_status'))

    op.drop_table('ai_model_registry')
    with op.batch_alter_table('ai_mlops_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_mlops_logs_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_ai_mlops_logs_event_type'))

    op.drop_table('ai_mlops_logs')
    # ### end Alembic commands ###
